### ISSUE TITLE
Pytest error 

### ISSUE THREAD

**Issue by nandezgarcia** [avacaondata/nlpboost#8]
I receive the next message when I run the test:

ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov-report --cov-report term --cov-config=.coveragerc --cov=src --instafail --pycodestyle --pydocstyle .
  inifile: /home/andres/Desarrollo/Desarrollo/Python/Doctorado/PruebasDeModelos/nlpboost/setup.cfg
  rootdir: /home/andres/Desarrollo/Desarrollo/Python/Doctorado/PruebasDeModelos/nlpboost

some idea?

Thanks!

**Comment by nandezgarcia** [comment]
solved. I needed to have the following packages installed:

pip install pytest-cov
pip install pytest-pycodestyle
pip install pytest-pydocstyle
pip install pytest-instafail

Good work, Alejandro.

**Comment by avacaondata** [comment]
Thank you very much :) 

I'm glad you solved the error. Maybe these dependencies should be included in requirements.txt.
